/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package obc;

import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.*;

public class CarTest {
    @Test public void testCarCanPark() {
        Car car = new Car();
        ParkingLot parkingLot = new ParkingLot(1);
        car.park(parkingLot);
        assertTrue(car.isParked());
    }
}
